services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mellon_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123 # Βάλε έναν δυνατό κωδικό
    networks:
      - mellon-net

networks:
  mellon-net:
    driver: bridge